name: Check Backend Files

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-backend-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List backend files
        id: list-files
        run: |
          cd backend  # Change directory to your backend folder
          BACKEND_FILES=$(find . -type f)
          echo "::set-output name=files::$BACKEND_FILES"

      - name: Check for Python files
        id: check-python
        run: |
          FILES="$GITHUB_WORKSPACE/${{ steps.list-files.outputs.files }}"
          if [[ $(echo "$FILES" | grep -v '\.py$') ]]; then
            echo "::set-output name=python-files::true"
          else
            echo "::set-output name=python-files::false"
          fi

      - name: Comment on pull request (if Python files found)
        if: steps.check-python.outputs.python-files == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { github, context } = require('@actions/github');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `@${{ github.actor }} :white_check_mark: Python files found in the backend directory.`
            });

      - name: Comment on pull request (if no Python files)
        if: steps.check-python.outputs.python-files == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { github, context } = require('@actions/github');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `@${{ github.actor }} :x: No Python files found in the backend directory.`
            });
