name: Backend Pipeline

on:
  push:
    branches: master
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run app.py
      run: |
        cd backend
        python app.py

    - name: Set outcome
      id: result
      run: echo "::set-output name=status::$(cat $GITHUB_WORKSPACE/status.txt)"

    - name: Display status
      if: steps.result.outputs.status == 'True'
      run: echo "Condition is True ✅"
      
    - name: Display status
      if: steps.result.outputs.status == 'False'
      run: echo "Condition is False ❌"
