on: [push, workflow_dispatch]

jobs:
  test-job:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - run: python "set.py"
        shell: bash
        id: name
        
      - run: echo "-> ${{ steps.name.outputs.name }}"         # prints the output which was set in set.py