name: workflow-conditional check

on: 
  push:
    branches:
      - dev
    paths:
      - backend/**
  

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: running python file
        run: python "set.py"
        shell: bash
        id: name


      - name: runnning
        run: echo "-> ${{ steps.name.outputs.name }}"        


      - name: Set output to environment variable
        run: echo "NAME=${{ steps.name.outputs.name }}" >> $GITHUB_ENV

