on: [push, workflow_dispatch]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: running python file
        run: python "set.py"
        shell: bash
        id: name


      - name: runnning
        run: echo "-> ${{ steps.name.outputs.name }}"        


      - name: Check output
        run: |
          if [ "${{ steps.name.outputs.name }}" = "True" ]; then
            echo "-> It's True"
          else
            echo "-> It's False"
            exit 1
          fi
        shell: bash