name: Backend Pipeline

on:
  push:
    branches: master
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run app.py
      run: |
        cd backend
        python app.py

    - name: Post comment on PR
      if: ${{ always() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npm install -g @octokit/cli
        octokit issues create-comment \
          --repo $GITHUB_REPOSITORY \
          --issue ${{ github.event.pull_request.number }} \
          --body "Workflow completed successfully! :white_check_mark:"
