name: pullrequest-file
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  your_job_name:
    runs-on: ubuntu-latest

    steps:
      - name: Your First Step
        run: echo "This is your first step"

      # Add more steps as needed

      - name: Install octokit CLI
        run: npm install -g @octokit/cli

      - name: Comment on PR with status
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          octokit issues create-comment \
            --repo $GITHUB_REPOSITORY \
            --issue ${{ github.event.pull_request.number }} \
            --body "Workflow completed :white_check_mark:"
